return {
	GAME_BUILD = "5-ac-debug-safe",
	BOOST_WALK_SPEED = 28,
	BOOST_SPRINT_SPEED = 36,
	FLIGHT_SPEED = 90,
	FLIGHT_BOOST_SPEED = 140,
	ZOOM_FOV = 12,
	HIT_RATE_WINDOW = 2.5,
	HIT_RATE_SAFE_MAX_RATIO = 0.72,
	HIT_RATE_BURST_MAX = 6,
	HIT_RATE_SAFE_MIN_SPREAD = 0.4,
}
