return {
	GAME_BUILD = "3-optimized",
	MAX_SAFE_WALKSPEED = 40,
	MAX_SPRINT_SPEED = 35,
	MAX_FLY_SPEED = 120,
	MAX_SAFE_JUMP = 75,
	DEFAULT_AIM_PARTS = { "Head", "Torso", "HumanoidRootPart", "UpperTorso" },
	DEFAULT_ATTACK_RANGE = 250,
	ENEMY_CACHE_INTERVAL = 0.05,
	SILENT_AIM_CACHE_TTL = 0.035,
	WEAPON_TICK_INTERVAL = 0.15,
	MAX_ESP_ENEMIES = 40,
	MAX_ESP_PLAYERS = 20,
}
