return {
	GAME_BUILD = "4-debug-fix20",
	MAX_SAFE_WALKSPEED = 40,
	MAX_SPRINT_SPEED = 35,
	MAX_FLY_SPEED = 120,
	MAX_SAFE_JUMP = 75,
	DEFAULT_AIM_PARTS = { "Head", "Torso", "HumanoidRootPart", "UpperTorso" },
	DEFAULT_ATTACK_RANGE = 250,
	DEFAULT_GRENADE_CAP = 5,
	AFK_IDLE_THRESHOLD = 600,
	AFK_BACKUP_INTERVAL = 540,
	ENEMY_CACHE_INTERVAL = 0.05,
	SILENT_AIM_CACHE_TTL = 0.035,
	WEAPON_TICK_INTERVAL = 0.15,
	MAX_ESP_ENEMIES = 40,
	MAX_ESP_PLAYERS = 20,
	LOBBY_AUTO_INTERVAL = 0.5,
	GUN_CRATE_BATCHES = { 1, 25, 50, 200 },
	PET_CRATE_BATCHES = { 1, 25, 50, 200 },
	OUTFIT_CRATE_BATCHES = { 1, 5, 10 },
	OUTFIT_ROLL_TYPES = {
		"Random",
		"Hat",
		"TorsoAccessory",
		"LegAccessory",
		"FaceAccessory",
		"ArmAccessory",
		"BackAccessory",
		"Gloves",
		"Shoes",
		"Hair",
		"Shirt",
		"Pants",
		"HairColor",
		"SkinColor",
		"Face",
	},
	PET_RARITY_ORDER = {
		"common",
		"uncommon",
		"rare",
		"epic",
		"legendary",
		"godly",
		"immortal",
		"cosmic",
		"celestial",
		"awakened",
		"transcendent",
		"zenith",
		"luminescent",
	},
	PET_BASE_WEIGHTS = {
		common = 49.794252,
		uncommon = 25,
		rare = 15,
		epic = 7,
		legendary = 2.5,
		godly = 0.5,
		immortal = 0.18,
		cosmic = 0.025,
		celestial = 0.0005,
		awakened = 0.0002,
		transcendent = 0.00004,
		zenith = 8e-6,
		luminescent = 1.5e-7,
	},
}
