return {
	ShowHUD = true,
	TickInterval = 0.2,
	SearchInterval = 0.35,
	CombatInterval = 0.12,
	ShopInterval = 2,

	SpeedBoost = false,
	WalkSpeed = 32,
	AlwaysSprint = false,
	SprintSpeed = 23,
	JumpBoost = false,
	JumpPower = 50,
	NoClip = false,
	Fly = false,
	FlySpeed = 50,
	FullBright = false,
	CameraFOV = 70,
	AntiAfk = true,

	AutoRedeemCode = false,
	RedeemCodeText = "",

	AutoDailyReward = false,
	AutoDailyQuest = false,
	AutoSearch = false,
	SearchRange = 18,

	AutoAttack = false,
	AutoEquipBest = false,
	AimAssist = false,
	AimFOV = 120,
	AttackRange = 80,

	AutoSpinWheel = false,
	SpinWheelSubtype = "Classic Box",
	AutoOpenBoxes = false,
	AutoToolShopBuy = false,
	ToolShopItem = "Pistol",
	AutoClaimGifts = false,
	AutoBuyRobuxBoxes = false,
	RobuxBoxName = "Classic Box",
	RobuxBoxPack = "1 Boxes",

	AutoSkipTutorial = false,
	DisableWeaponPopups = false,
	YoutubeMode = false,

	ESP = false,
	ESPSnaplines = false,
	MonsterESP = false,
	MonsterESPBoxes = false,
	SearchESP = false,
	CoinESP = false,
	MysteryBoxESP = false,
	ShowAimFOV = false,

	TeleportLevel = "Lobby",
}
