return {
	ShowHUD = true,
	TickInterval = 0.12,
	CombatInterval = 0.08,

	SpeedBoost = false,
	SpeedBoostSafe = true,
	WalkSpeed = 28,
	AlwaysSprint = false,
	InfiniteStamina = false,
	NoClip = false,
	Fly = false,
	FlyMode = "CFrame",
	FlySpeed = 28,
	FlySafeSpeed = true,
	FlyNetworkOwner = false,
	FlySuppressFell = true,
	VehicleFlyAutoEnter = true,
	VehicleFlyEnterRange = 25,
	RemoteProbeLog = true,
	ProbeAutoLog = true,
	ProbeLogInterval = 10,
	FullBright = false,
	AntiAfk = true,

	SilentAim = false,
	AutoShoot = false,
	AimAtHead = true,
	AttackRange = 200,
	AimFOV = 220,
	ShowAimFOV = false,

	ESP = false,
	ESPSnaplines = false,
	ESPRange = 500,

	LootESP = false,
	LootESPRange = 400,
	LootESPMaxItems = 80,
	LootESPShowDistance = true,
	LootESPShowCategory = false,
	LootESPUseColors = true,
	LootESPTextSize = 13,
	LootESPFilter = "All",

	AutoLoot = false,
	AutoLootRange = 12,
	AutoLootFilter = "All",
}
