return {
	GAME_BUILD = "1.0.12",
	MAX_WALK_SPEED = 40,
	MAX_FLY_SPEED = 50,
	SAFE_FLY_SPEED = 28,
	VEHICLE_FLY_ENTER_RANGE = 25,
	DEFAULT_AIM_FOV = 220,
	SILENT_AIM_CACHE_TTL = 0.08,
	FLY_MODES = { "CFrame", "Velocity", "Vehicle" },
	DEFAULT_ATTACK_RANGE = 200,
	MAX_ESP_DIST = 2000,
	DEFAULT_ESP_RANGE = 500,
	MAX_LOOT_ESP_RANGE = 2000,
	DEFAULT_LOOT_ESP_RANGE = 400,
	DEFAULT_LOOT_ESP_MAX = 80,
	DEFAULT_PROBE_LOG_INTERVAL = 10,
	MAX_ESP_PLAYERS = 24,
	MAX_ESP_LOOT = 200,
	LOOT_SCAN_INTERVAL = 0.35,
	LOOT_PICKUP_RANGE = 12,
	AUTO_LOOT_INTERVAL = 0.2,
	LOOT_FILTER_OPTIONS = {
		"All",
		"Guns",
		"Ammo",
		"Medical",
		"Food",
		"Clothing",
		"Melee",
		"Utility",
		"Vehicles",
	},
	LOOT_ESP_COLORS = {
		Gun = Color3.fromRGB(255, 120, 90),
		Primary = Color3.fromRGB(255, 120, 90),
		Secondary = Color3.fromRGB(255, 150, 90),
		Ammo = Color3.fromRGB(255, 220, 80),
		Medical = Color3.fromRGB(90, 220, 140),
		Food = Color3.fromRGB(140, 200, 255),
		Clothing = Color3.fromRGB(180, 140, 255),
		Melee = Color3.fromRGB(255, 90, 160),
		Utility = Color3.fromRGB(160, 220, 255),
		Vehicles = Color3.fromRGB(120, 180, 255),
		Other = Color3.fromRGB(120, 220, 255),
	},
	LOOT_CATEGORY_KEYWORDS = {
		Medical = {
			"bandage",
			"morphine",
			"epinephrine",
			"blood",
			"saline",
			"charcoal",
			"tetracycline",
			"vitamin",
			"disinfect",
			"painkiller",
			"iodine",
		},
		Food = {
			"beans",
			"soup",
			"peach",
			"tactical",
			"water",
			"soda",
			"milk",
			"meat",
			"apple",
			"cereal",
			"rice",
			"pasta",
			"can",
			"drink",
		},
		Clothing = {
			"shirt",
			"pants",
			"jacket",
			"boots",
			"hat",
			"vest",
			"gloves",
			"mask",
			"helm",
			"coat",
			"hoodie",
		},
		Melee = {
			"knife",
			"axe",
			"machete",
			"bat",
			"sword",
			"cleaver",
		},
		Utility = {
			"binocular",
			"compass",
			"map",
			"flare",
			"radio",
			"lockpick",
			"rope",
			"toolbox",
			"nails",
			"plank",
		},
		Vehicles = {
			"wheel",
			"spark",
			"radiator",
			"battery",
			"engine",
			"car",
			"truck",
		},
	},
	SHOTGUN_NAMES = { "Shotgun", "Maverick", "Auto-5", "M870", "M1014", "AA-12" },
	AIM_PARTS = { "SmallHead", "SmallTorso", "Head", "HumanoidRootPart" },
	HEAD_AIM_PARTS = { "SmallHead", "Head" },
	BODY_AIM_PARTS = { "SmallTorso", "Torso", "HumanoidRootPart" },
}
